project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Modeling"
  subtitle: "Political identity and affection in Europe"
  author: 
    - Yannick Diehl
    - Isabelle Borucki
  date: today
  favicon: images/logo.png
  search: true
  repo-url: https://github.com/YannickDiehl/MultilevelModelingUMR23
  sharing: [twitter, facebook]
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - module1.qmd
    - module2.qmd
    - references.qmd
    
comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo



