project:
  type: book
  output-dir: docs

book:
  title: "Multilevel models on political identity and affection in Europe"
  author: "Yannick Diehl"
  date: "14. April 2023"
  search: true
  repo-url: https://github.com/YannickDiehl/MultilevelModelingUMRSoSe23
  sharing: [twitter, facebook]
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo



