# Module 1: Multiple Regression

The aim of these exercises is to gain practical experience of the application and interpretation of multiple regression.

## Introduction to the European Social Survey 10 Dataset

You will be analysing data from the [European Social Survey 10](https://ess-search.nsd.no/en/study/172ac431-2a06-41df-9dab-c1fd8f3877e7) from 2020, a european wide representative survey. It is a cross-national survey with a mission to monitor and interpret changing attitudes and values across Europe, investigate how they interact with changing institutions, advance cross-national survey measurement methods, and develop social indicators. Since its establishment in 2001, the survey has been administered in 40 countries, using strict random probability sampling, achieving high response rates, and implementing rigorous translation protocols.

::: {.callout-note}
The European Social Survey (ESS) conducted face-to-face interviews for its data collection, but due to the COVID-19 pandemic, nine countries switched to self-completion methods while 22 countries continued with face-to-face interviews, with the option of using video interviews as a backup. Caution is advised when comparing data between countries using different approaches. The fieldwork for Round 10 was carried out over a longer period than usual, and timing may be important due to pandemic-related attitudinal and behavioral changes. The survey covers 32 countries and includes two new modules, and the ESS has been established as a European Research Infrastructure Consortium since Round 7.
:::



We use data from seven cohorts of young people collected in the first sweep of the study, carried out at the end of the final year of compulsory schooling (aged 16-17) when most sample members had taken Standard grades.2 These are subject-based examinations, typically taken in up to eight subjects. Each subject is graded on a scale from 1 (highest) to 7 (lowest). The dependent variable is a total attainment score calculated by assigning 7 points for a ‘1’, 6 for a ‘2’ and so on.
